"""
Hidden AI-generated reference corpus for single-file analysis.

Contains a diverse set of AI-generated text samples across different
topics and writing styles. These texts are used as comparison targets
when a user uploads a single file for plagiarism analysis.

The texts are intentionally kept in the backend only — they are never
exposed through the API or visible in the frontend.
"""

REFERENCE_TEXTS = {
    "ai_essay_education": {
        "title": "AI Reference — Education",
        "text": (
            "Education is the cornerstone of human development and plays a crucial role "
            "in shaping the future of society. Through education, individuals gain the "
            "knowledge and skills necessary to navigate the complexities of modern life. "
            "The importance of education cannot be overstated, as it empowers people to "
            "make informed decisions, contribute meaningfully to their communities, and "
            "pursue their personal and professional goals.\n\n"
            "In recent years, the landscape of education has undergone significant "
            "transformation driven by technological advancements. Digital platforms and "
            "online learning tools have made education more accessible than ever before, "
            "breaking down geographical barriers and providing opportunities for lifelong "
            "learning. These developments have particularly benefited individuals in "
            "underserved communities who previously had limited access to quality "
            "educational resources.\n\n"
            "Furthermore, the integration of artificial intelligence and machine learning "
            "into educational systems has opened up new possibilities for personalized "
            "learning experiences. Adaptive learning platforms can now tailor content to "
            "individual students' needs, pace, and learning styles, ensuring that each "
            "learner receives the support they need to succeed. This personalized approach "
            "has shown promising results in improving student outcomes and engagement.\n\n"
            "However, it is important to acknowledge the challenges that come with these "
            "advancements. Issues such as the digital divide, data privacy concerns, and "
            "the need for teacher training in new technologies must be addressed to ensure "
            "that the benefits of modern education are equitably distributed. Policymakers "
            "and educators must work together to create inclusive and effective educational "
            "frameworks that prepare students for the demands of the 21st century."
        ),
    },
    "ai_essay_technology": {
        "title": "AI Reference — Technology",
        "text": (
            "Technology has fundamentally transformed the way we live, work, and "
            "communicate in the modern world. From smartphones to artificial intelligence, "
            "technological innovations continue to reshape every aspect of human existence. "
            "The rapid pace of technological advancement has created both unprecedented "
            "opportunities and significant challenges for individuals and societies alike.\n\n"
            "One of the most significant developments in recent years has been the rise of "
            "artificial intelligence and its applications across various industries. Machine "
            "learning algorithms are now being used to diagnose diseases, optimize supply "
            "chains, and even create art. These applications demonstrate the versatile "
            "nature of AI technology and its potential to solve complex problems that were "
            "previously considered beyond the reach of computational methods.\n\n"
            "The internet of things represents another transformative technological trend "
            "that is reshaping our daily lives. By connecting everyday objects to the "
            "internet, IoT technology enables seamless communication between devices, "
            "creating smart homes, smart cities, and intelligent transportation systems. "
            "This interconnected ecosystem of devices has the potential to improve "
            "efficiency, reduce waste, and enhance the quality of life for billions of "
            "people around the world.\n\n"
            "Despite these remarkable advances, it is essential to consider the ethical "
            "implications of emerging technologies. Questions surrounding data privacy, "
            "algorithmic bias, and the displacement of workers by automation require "
            "thoughtful consideration and proactive policy responses. As we continue to "
            "embrace technological innovation, we must ensure that these powerful tools "
            "are developed and deployed responsibly for the benefit of all humanity."
        ),
    },
    "ai_essay_environment": {
        "title": "AI Reference — Environment",
        "text": (
            "Climate change represents one of the most pressing challenges facing our "
            "planet today. The scientific consensus is clear: human activities, particularly "
            "the burning of fossil fuels and deforestation, are contributing to a rapid "
            "increase in global temperatures. This warming trend has far-reaching "
            "consequences for ecosystems, weather patterns, and human communities "
            "around the world.\n\n"
            "The effects of climate change are already being felt across the globe. Rising "
            "sea levels threaten coastal communities, while extreme weather events such as "
            "hurricanes, droughts, and wildfires are becoming more frequent and severe. "
            "These changes disproportionately affect vulnerable populations in developing "
            "countries who have contributed least to the problem but lack the resources "
            "to adapt to its consequences.\n\n"
            "Addressing climate change requires a comprehensive and coordinated global "
            "response. Transitioning to renewable energy sources, implementing carbon "
            "pricing mechanisms, and investing in sustainable infrastructure are all "
            "critical components of an effective climate strategy. Additionally, protecting "
            "and restoring natural ecosystems such as forests, wetlands, and oceans can "
            "serve as important carbon sinks and provide numerous co-benefits for "
            "biodiversity and human well-being.\n\n"
            "Individual actions also play a significant role in combating climate change. "
            "By making conscious choices about energy consumption, transportation, and "
            "dietary habits, individuals can collectively make a meaningful impact on "
            "reducing greenhouse gas emissions. Education and awareness campaigns are "
            "essential for empowering people to take action and advocate for policies "
            "that prioritize environmental sustainability and climate resilience."
        ),
    },
    "ai_essay_health": {
        "title": "AI Reference — Health",
        "text": (
            "The field of healthcare has experienced remarkable advancements in recent "
            "decades, driven by breakthroughs in medical research, technology, and our "
            "understanding of human biology. These developments have led to significant "
            "improvements in disease prevention, diagnosis, and treatment, ultimately "
            "contributing to increased life expectancy and quality of life for people "
            "around the world.\n\n"
            "Precision medicine represents a paradigm shift in healthcare, moving away "
            "from a one-size-fits-all approach toward treatments tailored to individual "
            "patients based on their genetic makeup, lifestyle, and environment. Advances "
            "in genomics and bioinformatics have made it possible to identify specific "
            "genetic markers associated with various diseases, enabling earlier detection "
            "and more targeted therapeutic interventions.\n\n"
            "Mental health has emerged as a critical area of focus in global healthcare "
            "discussions. The recognition that mental health is equally important as "
            "physical health has led to increased investment in mental health services "
            "and research. Innovative approaches such as digital therapeutics, "
            "telepsychiatry, and mindfulness-based interventions are expanding access "
            "to mental health support and reducing the stigma associated with seeking "
            "help for psychological conditions.\n\n"
            "Despite these positive developments, significant disparities in healthcare "
            "access and outcomes persist globally. Addressing these inequities requires "
            "a multi-faceted approach that includes strengthening healthcare systems, "
            "training more healthcare professionals, and leveraging technology to deliver "
            "care to underserved populations. International cooperation and sustained "
            "investment in public health infrastructure are essential for building a "
            "healthier and more equitable world."
        ),
    },
    "ai_essay_economics": {
        "title": "AI Reference — Economics",
        "text": (
            "The global economy has undergone significant structural changes in recent "
            "years, influenced by factors such as globalization, technological innovation, "
            "and shifting demographic patterns. These changes have created new economic "
            "opportunities while also presenting challenges for workers, businesses, and "
            "governments around the world.\n\n"
            "The rise of the digital economy has fundamentally altered traditional business "
            "models and labor markets. E-commerce platforms, sharing economy services, and "
            "remote work technologies have created new avenues for economic activity while "
            "disrupting established industries. This digital transformation has accelerated "
            "the need for workers to acquire new skills and adapt to rapidly changing "
            "job requirements.\n\n"
            "Sustainable economic development has become a central priority for "
            "policymakers and business leaders alike. The concept of a circular economy, "
            "which emphasizes reducing waste, reusing materials, and recycling resources, "
            "offers a promising framework for achieving economic growth while minimizing "
            "environmental impact. Companies that embrace sustainability practices often "
            "find that they can reduce costs, attract conscious consumers, and build "
            "long-term resilience.\n\n"
            "Income inequality remains one of the most significant economic challenges "
            "facing societies today. The growing gap between the wealthy and the poor has "
            "implications for social cohesion, political stability, and economic mobility. "
            "Addressing this challenge requires thoughtful policy interventions, including "
            "progressive taxation, investment in education and job training, and the "
            "strengthening of social safety nets to ensure that economic prosperity is "
            "shared broadly across society."
        ),
    },
    "ai_essay_history": {
        "title": "AI Reference — History",
        "text": (
            "Throughout the course of human history, civilizations have risen and "
            "fallen, each leaving behind a legacy that continues to shape the modern "
            "world. The study of history is not merely an academic exercise; it is a "
            "vital tool for understanding the present and preparing for the future. "
            "By examining the successes and failures of past societies, we can gain "
            "valuable insights into the forces that drive social change.\n\n"
            "The ancient civilizations of Mesopotamia, Egypt, Greece, and Rome laid "
            "the foundations for many of the political, philosophical, and scientific "
            "traditions that persist today. The development of writing systems, legal "
            "codes, and democratic institutions during this period represented "
            "monumental achievements that would influence countless generations. "
            "These early societies demonstrated humanity's capacity for innovation "
            "and organization on a grand scale.\n\n"
            "The medieval period, often characterized as an era of stagnation, was "
            "in fact a time of significant cultural and intellectual development. "
            "The preservation of classical knowledge by Islamic scholars, the "
            "establishment of universities in Europe, and the flourishing of art "
            "and architecture during this period all contributed to the eventual "
            "emergence of the Renaissance and the Scientific Revolution.\n\n"
            "In the modern era, the forces of industrialization, nationalism, and "
            "globalization have profoundly transformed human societies. The rapid "
            "pace of technological change has accelerated the interconnectedness "
            "of nations and cultures, creating both opportunities and challenges "
            "for the global community. Understanding these historical processes "
            "is essential for navigating the complexities of the contemporary world."
        ),
    },
    "ai_essay_psychology": {
        "title": "AI Reference — Psychology",
        "text": (
            "Psychology, the scientific study of the mind and behavior, has made "
            "tremendous strides in helping us understand what drives human thought, "
            "emotion, and action. From the foundational theories of Sigmund Freud "
            "to the modern advances in cognitive neuroscience, the field has "
            "continuously evolved to provide deeper insights into the complexities "
            "of the human experience.\n\n"
            "Cognitive psychology, one of the most influential branches of the "
            "discipline, focuses on understanding mental processes such as "
            "perception, memory, attention, and problem-solving. Research in this "
            "area has revealed that human cognition is not always rational or "
            "objective. Cognitive biases, heuristics, and mental shortcuts often "
            "influence our decision-making in ways that we are not consciously aware "
            "of, leading to systematic errors in judgment.\n\n"
            "Social psychology examines how individuals are influenced by the "
            "presence and behavior of others. Landmark studies such as Stanley "
            "Milgram's obedience experiments and Philip Zimbardo's Stanford Prison "
            "Experiment have demonstrated the powerful impact of social situations "
            "on individual behavior. These findings have important implications for "
            "understanding phenomena such as conformity, prejudice, and group "
            "dynamics in various social contexts.\n\n"
            "The integration of psychology with neuroscience has opened up exciting "
            "new avenues for research and treatment. Advances in brain imaging "
            "technology have allowed researchers to observe neural activity in real "
            "time, providing unprecedented insights into the biological basis of "
            "mental health conditions. This interdisciplinary approach holds great "
            "promise for developing more effective interventions for psychological "
            "disorders and improving overall mental well-being."
        ),
    },
    "ai_essay_science": {
        "title": "AI Reference — Science",
        "text": (
            "Scientific inquiry has been the driving force behind humanity's "
            "understanding of the natural world. Through systematic observation, "
            "experimentation, and analysis, scientists have uncovered the fundamental "
            "laws that govern the universe, from the smallest subatomic particles to "
            "the vast expanses of cosmic space. The scientific method, with its "
            "emphasis on evidence-based reasoning, remains the most reliable approach "
            "to acquiring knowledge about the physical world.\n\n"
            "The field of physics has experienced remarkable breakthroughs over the "
            "past century. Albert Einstein's theory of relativity revolutionized our "
            "understanding of space, time, and gravity, while quantum mechanics "
            "revealed the strange and counterintuitive behavior of matter at the "
            "atomic scale. These two theoretical frameworks, though seemingly "
            "incompatible, have each been confirmed by extensive experimental "
            "evidence and have led to numerous technological applications.\n\n"
            "Biology has been transformed by the discovery of DNA and the subsequent "
            "development of molecular biology and genetics. The Human Genome Project, "
            "completed in 2003, provided a comprehensive map of human genetic "
            "information and opened new frontiers in personalized medicine and "
            "genetic engineering. Technologies such as CRISPR-Cas9 gene editing "
            "have further expanded the possibilities for treating genetic diseases "
            "and improving agricultural productivity.\n\n"
            "The importance of scientific literacy in the modern world cannot be "
            "overstated. As society faces complex challenges such as climate change, "
            "emerging infectious diseases, and resource depletion, the ability to "
            "understand and critically evaluate scientific evidence is essential for "
            "making informed decisions at both the individual and policy levels."
        ),
    },
    "ai_essay_philosophy": {
        "title": "AI Reference — Philosophy",
        "text": (
            "Philosophy, the love of wisdom, has been a cornerstone of human "
            "intellectual endeavor since ancient times. Philosophical inquiry seeks "
            "to address fundamental questions about existence, knowledge, ethics, "
            "and the nature of reality. These questions, though they may never be "
            "definitively answered, continue to challenge and inspire thinkers "
            "across cultures and generations.\n\n"
            "Ethics, one of the central branches of philosophy, is concerned with "
            "determining what is morally right and wrong. Major ethical frameworks, "
            "including consequentialism, deontology, and virtue ethics, offer "
            "different approaches to evaluating the morality of human actions. "
            "Consequentialism judges actions based on their outcomes, deontology "
            "focuses on adherence to moral rules and duties, while virtue ethics "
            "emphasizes the development of good character traits.\n\n"
            "Epistemology, the study of knowledge, examines the nature, sources, "
            "and limits of human understanding. Questions about what constitutes "
            "justified belief, the reliability of sensory experience, and the "
            "possibility of objective truth have been debated by philosophers for "
            "millennia. In the age of information and misinformation, these "
            "epistemological questions have taken on renewed practical significance.\n\n"
            "The relevance of philosophy extends far beyond the academic sphere. "
            "Philosophical thinking provides tools for critical analysis, logical "
            "reasoning, and ethical decision-making that are valuable in virtually "
            "every profession and aspect of daily life. By engaging with philosophical "
            "questions, individuals can develop a deeper understanding of themselves "
            "and the world around them."
        ),
    },
    "ai_essay_sociology": {
        "title": "AI Reference — Sociology",
        "text": (
            "Sociology provides a systematic framework for understanding the "
            "structures, institutions, and processes that shape human societies. "
            "By examining patterns of social behavior, inequality, and cultural "
            "norms, sociologists seek to explain how individuals and groups interact "
            "within the broader context of social systems. This discipline offers "
            "crucial insights into the forces that bind communities together and "
            "the tensions that can tear them apart.\n\n"
            "Social stratification, the hierarchical arrangement of individuals "
            "and groups within a society, is one of the most extensively studied "
            "topics in sociology. Class, race, gender, and other social categories "
            "intersect in complex ways to determine individuals' access to resources, "
            "opportunities, and power. Understanding these intersecting dimensions "
            "of inequality is essential for developing policies that promote social "
            "justice and equal opportunity.\n\n"
            "The process of socialization, through which individuals learn the norms, "
            "values, and expectations of their culture, plays a fundamental role in "
            "shaping identity and behavior. Family, education, media, and peer groups "
            "all serve as agents of socialization, transmitting cultural knowledge "
            "and reinforcing social norms from one generation to the next. The study "
            "of socialization helps us understand how societies maintain continuity "
            "while also adapting to change.\n\n"
            "In an increasingly globalized world, sociology has expanded its focus to "
            "examine transnational processes and their impact on local communities. "
            "Migration, cultural exchange, and global economic integration have "
            "created new forms of social organization and identity that challenge "
            "traditional sociological categories. These developments underscore the "
            "need for sociological analysis that is both globally informed and "
            "locally sensitive."
        ),
    },
    "ai_essay_literature": {
        "title": "AI Reference — Literature & Arts",
        "text": (
            "Literature and the arts serve as mirrors of the human condition, "
            "reflecting the hopes, fears, and aspirations of societies across time "
            "and space. Through creative expression, artists and writers explore "
            "the depths of human experience, giving voice to emotions and ideas "
            "that might otherwise remain unarticulated. The study of literature "
            "and arts enriches our understanding of diverse perspectives and "
            "fosters empathy and critical thinking.\n\n"
            "The literary canon encompasses a vast and diverse body of works that "
            "have shaped cultural consciousness throughout history. From the epic "
            "poems of Homer to the modernist novels of Virginia Woolf, literary "
            "works have grappled with timeless themes such as love, death, identity, "
            "and the search for meaning. These texts continue to resonate with "
            "contemporary readers because they address universal aspects of the "
            "human experience.\n\n"
            "The visual arts, including painting, sculpture, and photography, have "
            "undergone radical transformations over the centuries. Movements such as "
            "Impressionism, Cubism, and Abstract Expressionism challenged traditional "
            "notions of representation and pushed the boundaries of artistic "
            "expression. In the digital age, new forms of art such as digital "
            "media, interactive installations, and virtual reality experiences are "
            "expanding the definition of what constitutes art.\n\n"
            "The role of arts education in fostering creativity and critical thinking "
            "has been widely recognized by educators and researchers. Exposure to "
            "literature and the arts helps individuals develop cultural awareness, "
            "emotional intelligence, and the ability to think imaginatively. These "
            "skills are increasingly valued in a world that demands innovative "
            "solutions to complex problems."
        ),
    },
    "ai_essay_business": {
        "title": "AI Reference — Business & Entrepreneurship",
        "text": (
            "The world of business and entrepreneurship is characterized by constant "
            "innovation, competition, and adaptation. Successful businesses must "
            "navigate complex market dynamics, anticipate consumer needs, and "
            "leverage emerging technologies to maintain a competitive edge. The "
            "principles of effective management, strategic planning, and financial "
            "stewardship are essential for building sustainable enterprises in an "
            "increasingly volatile economic landscape.\n\n"
            "Entrepreneurship plays a vital role in driving economic growth and "
            "creating employment opportunities. Entrepreneurs identify unmet needs "
            "in the market and develop innovative products and services to address "
            "them. The entrepreneurial mindset, characterized by creativity, "
            "resilience, and a willingness to take calculated risks, is increasingly "
            "recognized as a valuable asset in both the private and public sectors.\n\n"
            "The digital revolution has fundamentally altered the business landscape, "
            "enabling companies to reach global markets with unprecedented speed and "
            "efficiency. E-commerce platforms, social media marketing, and data "
            "analytics have become essential tools for modern businesses seeking to "
            "understand and engage their target audiences. Companies that fail to "
            "embrace digital transformation risk being left behind by more agile "
            "and technologically savvy competitors.\n\n"
            "Corporate social responsibility has emerged as a key consideration for "
            "businesses in the 21st century. Consumers, investors, and regulators "
            "increasingly expect companies to operate in an environmentally and "
            "socially responsible manner. Businesses that integrate sustainability "
            "into their core strategies often find that doing good and doing well "
            "are not mutually exclusive goals."
        ),
    },
    "ai_essay_law": {
        "title": "AI Reference — Law & Justice",
        "text": (
            "The legal system serves as the backbone of an organized and just "
            "society, providing a framework for resolving disputes, protecting "
            "individual rights, and maintaining public order. The rule of law, "
            "which ensures that all individuals and institutions are accountable "
            "to laws that are publicly promulgated, equally enforced, and "
            "independently adjudicated, is a fundamental principle of democratic "
            "governance.\n\n"
            "Criminal justice systems around the world face ongoing challenges "
            "in balancing the imperatives of public safety with the protection of "
            "individual rights. Issues such as mass incarceration, racial disparities "
            "in sentencing, and the use of solitary confinement have prompted "
            "widespread calls for reform. Advocates for criminal justice reform "
            "argue that a greater emphasis on rehabilitation, restorative justice, "
            "and evidence-based policies can lead to more effective and equitable "
            "outcomes.\n\n"
            "International law has become increasingly important in a globalized "
            "world where transnational issues such as terrorism, environmental "
            "degradation, and human rights violations require coordinated responses. "
            "International treaties, conventions, and organizations provide "
            "mechanisms for cooperation among nations, though enforcement remains "
            "a significant challenge. The development of international criminal "
            "courts and tribunals represents an important step toward accountability "
            "for the most serious crimes.\n\n"
            "The intersection of technology and law presents both opportunities "
            "and challenges for legal systems. Issues such as data privacy, "
            "intellectual property in the digital age, and the regulation of "
            "artificial intelligence require legal frameworks that can keep pace "
            "with rapid technological change. Legal professionals must continuously "
            "adapt their knowledge and practices to address these emerging issues "
            "effectively."
        ),
    },
    "ai_essay_nutrition": {
        "title": "AI Reference — Nutrition & Wellness",
        "text": (
            "Nutrition is a fundamental determinant of health and well-being, "
            "influencing everything from physical growth and development to cognitive "
            "function and disease risk. A balanced diet that provides adequate amounts "
            "of essential nutrients is crucial for maintaining optimal health "
            "throughout the lifespan. Understanding the principles of nutrition "
            "empowers individuals to make informed choices about the foods they "
            "consume and their overall dietary patterns.\n\n"
            "The relationship between diet and chronic disease has been extensively "
            "studied by researchers around the world. Evidence consistently shows "
            "that diets rich in fruits, vegetables, whole grains, and lean proteins "
            "are associated with lower risks of heart disease, diabetes, and certain "
            "types of cancer. Conversely, diets high in processed foods, added "
            "sugars, and unhealthy fats contribute to the growing burden of "
            "non-communicable diseases in both developed and developing countries.\n\n"
            "The concept of food sustainability has gained significant attention "
            "in recent years as concerns about environmental impact and food security "
            "have intensified. Sustainable dietary practices, such as reducing food "
            "waste, choosing locally sourced produce, and incorporating more plant-"
            "based foods into meals, can contribute to both personal health and "
            "environmental conservation. These practices align with growing consumer "
            "demand for transparency and responsibility in food production.\n\n"
            "Public health initiatives aimed at improving nutrition literacy and "
            "access to healthy foods are essential for addressing health disparities. "
            "School nutrition programs, community gardens, and policies that promote "
            "affordable access to nutritious foods can help ensure that all "
            "individuals, regardless of socioeconomic status, have the opportunity "
            "to achieve and maintain good health through proper nutrition."
        ),
    },
    "ai_essay_computer_science": {
        "title": "AI Reference — Computer Science",
        "text": (
            "Computer science has emerged as one of the most dynamic and influential "
            "fields of study in the modern era. The discipline encompasses a broad "
            "range of topics, from theoretical foundations such as algorithms and "
            "computational complexity to practical applications in software "
            "engineering, data science, and cybersecurity. The pervasive impact of "
            "computing technology on every aspect of contemporary life underscores "
            "the importance of computer science education and research.\n\n"
            "Artificial intelligence and machine learning represent some of the most "
            "exciting frontiers in computer science. These technologies enable "
            "computers to learn from data, recognize patterns, and make decisions "
            "with minimal human intervention. Applications of AI and machine learning "
            "span diverse domains, including natural language processing, computer "
            "vision, autonomous vehicles, and medical diagnostics, demonstrating "
            "the transformative potential of these technologies.\n\n"
            "Cybersecurity has become a critical concern as our reliance on digital "
            "systems continues to grow. The increasing frequency and sophistication "
            "of cyber attacks pose significant threats to individuals, organizations, "
            "and governments. Developing robust security measures, training skilled "
            "cybersecurity professionals, and fostering a culture of security "
            "awareness are essential for protecting sensitive data and maintaining "
            "trust in digital infrastructure.\n\n"
            "The ethical dimensions of computing have gained prominence as technology "
            "becomes more deeply embedded in social and economic systems. Issues "
            "such as algorithmic bias, digital surveillance, and the societal impact "
            "of automation raise important questions about fairness, accountability, "
            "and transparency in the design and deployment of computing systems. "
            "Addressing these ethical challenges requires collaboration among "
            "computer scientists, policymakers, and communities."
        ),
    },
}


def get_reference_texts() -> dict[str, dict]:
    """Return the full reference corpus."""
    return REFERENCE_TEXTS


def get_reference_ids() -> list[str]:
    """Return the list of reference text IDs."""
    return list(REFERENCE_TEXTS.keys())
