# Generated by Django 5.2.11 on 2026-02-18 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(default='default', help_text='Detection provider/algorithm to use', max_length=50)),
                ('options', models.JSONField(blank=True, default=dict, help_text='User-selected detection options (e.g. sensitivity, n-gram size)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('minio_key', models.CharField(help_text='Object key in MinIO/S3 bucket', max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='detection.batch')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_pct', models.FloatField(help_text='Overall similarity percentage (0.0 – 100.0)')),
                ('details', models.JSONField(default=dict, help_text='Rich comparison data: fingerprint matches, flagged segments, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detection.batch')),
                ('doc_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_as_a', to='detection.document')),
                ('doc_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_as_b', to='detection.document')),
            ],
            options={
                'ordering': ['-similarity_pct'],
            },
        ),
    ]
